name: rigsat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+3

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0  
  firebase_auth: ^4.6.1  
  cloud_firestore: ^4.7.1
  hidden_drawer_menu: ^3.0.1
  intl: ^0.18.1
  provider: ^6.0.5
  google_fonts: ^4.0.3
  collection: ^1.15.0
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  outlined_text: ^1.0.1
  firebase_storage: ^11.2.2
  video_player: ^2.6.1
  image_picker: ^0.8.7+5
  flutter_spinkit: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/RigSat.jpg
    - assets/rp.png
    - assets/SmartPSS.png  