// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnmEGnIq_SbbFuaL3DDmBryoqVCHdFgf0',
    appId: '1:337056061459:web:df48dfe128a5bd68ce07e6',
    messagingSenderId: '337056061459',
    projectId: 'rigsat',
    authDomain: 'rigsat.firebaseapp.com',
    storageBucket: 'rigsat.appspot.com',
    measurementId: 'G-ZKPJ569CXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLDoy_fnvxeOl3bgBPPmGwC_pb9D32ULI',
    appId: '1:337056061459:android:ad394be1f6cf7810ce07e6',
    messagingSenderId: '337056061459',
    projectId: 'rigsat',
    storageBucket: 'rigsat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoLbaSvuaBeWE9F6iYsFxG6kne4xIXUgk',
    appId: '1:337056061459:ios:78611adf1be39e8ece07e6',
    messagingSenderId: '337056061459',
    projectId: 'rigsat',
    storageBucket: 'rigsat.appspot.com',
    iosClientId: '337056061459-dckt7me557oakk2k18t878764r7pbudk.apps.googleusercontent.com',
    iosBundleId: 'com.emaren.rigsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoLbaSvuaBeWE9F6iYsFxG6kne4xIXUgk',
    appId: '1:337056061459:ios:9ed833b252d3e72ece07e6',
    messagingSenderId: '337056061459',
    projectId: 'rigsat',
    storageBucket: 'rigsat.appspot.com',
    iosClientId: '337056061459-nqegcg7bsnd979lhg6qve2c150mh6lr4.apps.googleusercontent.com',
    iosBundleId: 'com.emaren.rigsat.RunnerTests',
  );
}
